export const ADMIN_ALL_REVIEWS_REQUEST = "ADMIN_ALL_REVIEWS_REQUEST";
export const ADMIN_ALL_REVIEWS_SUCCESS = "ADMIN_ALL_REVIEWS_SUCCESS";
export const ADMIN_ALL_REVIEWS_FAIL = "ADMIN_ALL_REVIEWS_FAIL";

export const ADMIN_DELETE_REVIEW_REQUEST = "ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS = "ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_FAIL = "ADMIN_DELETE_REVIEW_FAIL";
export const ADMIN_DELETE_REVIEW_RESET = "ADMIN_DELETE_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";