export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCTS_SUCCESS";
export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCTS_FAIL";

export const ADMIN_NEW_PRODUCT_REQUEST = "ADMIN_NEW_PRODUCT_REQUEST";
export const ADMIN_NEW_PRODUCT_SUCCESS = "ADMIN_NEW_PRODUCT_SUCCESS";
export const ADMIN_NEW_PRODUCT_RESET = "ADMIN_NEW_PRODUCT_RESET";
export const ADMIN_NEW_PRODUCT_FAIL = "ADMIN_NEW_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";